
services:
  mongodb:
    container_name: "mongodb"
    image: mongo:7.0.7
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

  cache:
    image: redis:6.2-alpine
    container_name: "redis"
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redisPassword --user redisName
    volumes: 
      - cache:/data

volumes:
  dbdata6:
  cache:
    driver: local
