properties:
  headers:
    properties:
      isdeleted:
        type: string
        enum:
          - 'true'
          - 'false'
    required:
      - isdeleted
    additionalProperties: true
additionalProperties: true
